# Generated by Django 4.1.3 on 2022-12-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_tour_user'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcomment',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_tour', to='tour.concretetour'),
        ),
        migrations.AlterField(
            model_name='tourfavorite',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tour', to='tour.concretetour'),
        ),
        migrations.AlterField(
            model_name='tourrating',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_tour', to='tour.concretetour'),
        ),
    ]
