# Generated by Django 4.1.3 on 2022-12-07 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_businessimage_image_and_more'),
        ('review', '0002_alter_guiderating_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiderating',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_guide', to='business.guide'),
        ),
    ]
