# Generated by Django 4.1.3 on 2022-11-26 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название компании')),
                ('image', models.ImageField(upload_to='media/business_profile_images')),
                ('desc', models.CharField(max_length=200, verbose_name='О компании')),
                ('phone', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=150, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=150, verbose_name='Адресс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль компании',
                'verbose_name_plural': 'Профили компаний',
            },
        ),
    ]
