# Generated by Django 4.1.3 on 2022-11-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='business.businessprofile', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.businessprofile', verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
