# Generated by Django 4.1.3 on 2022-12-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessimage',
            name='image',
            field=models.ImageField(upload_to='tour_images'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='image',
            field=models.ImageField(upload_to='business_images'),
        ),
    ]
