# Generated by Django 4.1.3 on 2022-11-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_guide_company_name_tour_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='id',
        ),
        migrations.AddField(
            model_name='guide',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, primary_key=True, serialize=False),
        ),
    ]
