# Generated by Django 4.1.3 on 2022-11-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_tour_company_name_remove_tour_guide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, primary_key=True, serialize=False),
        ),
    ]
