# Generated by Django 4.1.3 on 2022-12-01 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0002_guide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
    ]
