# Generated by Django 4.1.3 on 2022-11-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_businessprofile_id_businessprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='Электронная почта'),
        ),
    ]
