# Generated by Django 4.1.3 on 2022-11-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code_confirm_method',
        ),
        migrations.AddField(
            model_name='user',
            name='code_method',
            field=models.CharField(choices=[('email', 'E-MAIL'), ('phone', 'SMS')], default='phone', max_length=6),
        ),
    ]
