# Generated by Django 4.1.3 on 2022-11-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email'),
        ('account', '0002_remove_user_code_confirm_method_user_code_method'),
    ]

    operations = [
    ]
