# Generated by Django 4.1.3 on 2022-12-05 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='guide',
        ),
        migrations.AddField(
            model_name='concretetour',
            name='guide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tour_back', to='business.guide', verbose_name='Гид'),
            preserve_default=False,
        ),
    ]
