# Generated by Django 4.1.3 on 2022-12-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cashaback',
            new_name='cashback',
        ),
    ]
